history:
  - "ุงูุชุงุฑูุฎ"
  - "history"
  - "ูุตุทูุญ ุชุงุฑูุฎู"
  - "๐ ุงูุชุงุฑูุฎ"

geography:
  - "ุงูุฌุบุฑุงููุง"
  - "geography"
  - "ูุตุทูุญ ุฌุบุฑุงูู"
  - "๐บ๏ธ ุงูุฌุบุฑุงููุง"

unit-1:
  - "ุงููุญุฏุฉ ุงูุฃููู"
  - "unit 1"
  - "ูุญุฏุฉ 1"

unit-2:
  - "ุงููุญุฏุฉ ุงูุซุงููุฉ"
  - "unit 2"
  - "ูุญุฏุฉ 2"

unit-3:
  - "ุงููุญุฏุฉ ุงูุซุงูุซุฉ"
  - "unit 3"
  - "ูุญุฏุฉ 3"
