labels:
  - label: "history"
    pattern: ".*(التاريخ|history|مصطلح تاريخي|📚 التاريخ).*"

  - label: "geography"
    pattern: ".*(الجغرافيا|geography|مصطلح جغرافي|🗺️ الجغرافيا).*"

  - label: "unit-1"
    pattern: ".*(الوحدة الأولى|unit 1|وحدة 1).*"

  - label: "unit-2"
    pattern: ".*(الوحدة الثانية|unit 2|وحدة 2).*"

  - label: "unit-3"
    pattern: ".*(الوحدة الثالثة|unit 3|وحدة 3).*"
