- name: history
  description: history
  color: '#FBCA04'
- name: geography
  description: geography
  color: '#0052CC'
- name: unit-1
  description: unit-1
  color: '#C5DEF5'
- name: unit-2
  description: unit-2
  color: '#C5DEF5'
- name: unit-3
  description: unit-3
  color: '#C5DEF5'
