unit-1:
- changed-files:
  - any-glob-to-any-file: unit-1/**

unit-2:
- changed-files:
  - any-glob-to-any-file: unit-2/**

unit-3:
- changed-files:
  - any-glob-to-any-file: unit-3/**

meta-fix:
- changed-files:
  - any-glob-to-any-file: '*'

history:
- changed-files:
  - any-glob-to-any-file: **/history-*.md

history:
- changed-files:
  - any-glob-to-any-file: **/geography.md
