name: "๐ Fix Typo or Grammar"
description: ุณุงุนุฏูุง ูู ุชุตุญูุญ ุงูุฃุฎุทุงุก ุงูุจุณูุทุฉ
labels: [typo]
body:
  - type: input
    id: term
    attributes:
      label: ุงููุตุทูุญ ุงููุชุฃุซุฑ
      placeholder: ูุซุงู: ุงูุฏููุฉ ุงูุนุซูุงููุฉ
  - type: textarea
    id: issue
    attributes:
      label: ูุง ูู ุงูุฎุทุฃุ
      description: ุงุดุฑุญ ุงูุฎุทุฃ ุงููุบูู ุฃู ุงููุทุจุนู ุงูุฐู ูุงุญุธุชู.
  - type: textarea
    id: suggestion
    attributes:
      label: ุงูุชุตุญูุญ ุงูููุชุฑุญ
      placeholder: ุงูุชุจ ุงูุตูุงุบุฉ ุงูุตุญูุญุฉ ุฅุฐุง ููุช ุชุนุฑููุง.
