name: Auto Release Converted Files

on:
  push:
    branches:
      - main
    paths:
      - 'converted/**'

jobs:
  auto-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_latest_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump tag
        id: bump_tag
        run: |
          VERSION=$(echo "${{ steps.get_latest_tag.outputs.tag }}" | sed 's/^v//')
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          NEW_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          echo "New tag: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create new tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.bump_tag.outputs.new_tag }}
          git push origin ${{ steps.bump_tag.outputs.new_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_tag.outputs.new_tag }}
          name: Release ${{ steps.bump_tag.outputs.new_tag }}
          body: Auto release with converted files.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Converted Files
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_tag.outputs.new_tag }}
          files: converted/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
