name: Pull Request Labeler

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '(tree-wide)') && !contains(github.event.pull_request.title, '(treewide)') }}

    steps:
      - uses: actions/checkout@v4

      - name: Add pull request labels
        uses: actions/labeler@v5
        with:
          configuration-path: .github/pr-labeler.yml
          sync-labels: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
